name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ha-ha
        uses: ./.github/actions/joke-action
      - uses: actions/upload-artifact@v4.3.3
        name: upload build artifacts
        with:
          name: webapp
          path: ./test-upload.txt
          retention-days: 7
          overwrite: true
